// setp 1

// products
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
// wish list
// GET
export const GET_WHISH_LIST_START = "GET_WHISH_LIST_START";
export const GET_WHISH_LIST_SUCCESS = "GET_WHISH_LIST_SUCCESS";
export const GET_WHISH_LIST_FAIL = "GET_WHISH_LIST_FAIL";
// POST
export const POST_WHISH_LIST_START = "POST_WHISH_LIST_START";
export const POST_WHISH_LIST_SUCCESS = "POST_WHISH_LIST_SUCCESS";
export const POST_WHISH_LIST_FAIL = "POST_WHISH_LIST_FAIL";

// cart list
export const GET_CART_LIST_START = "GET_CART_LIST_START";
export const GET_CART_LIST_SUCCESS = "GET_CART_LIST_SUCCESS";
export const GET_CART_LIST_FAIL = "GET_CART_LIST_FAIL";
